from striprtf.striprtf import rtf_to_text
import numpy as np
from pathlib import Path
import re
import json

# === Set up paths ===
home = Path.home()
work_dir = home / "housing_project"
data = work_dir / "data"
minutes = data / "meeting_minutes"
minutes_raw = minutes / "raw"
minutes_clean = minutes / "processed"
text_dir = minutes / "text"
text_dir.mkdir(parents=True, exist_ok=True)

rtf = Path(f"{minutes_raw}/minutes_training_sample.rtf").read_text(encoding="utf-8", errors="ignore")
plain = rtf_to_text(rtf)
# now `plain` is the same text you see, with all the <<Project Start>> markers
blocks = re.findall(r"<<Project Start>>(.*?)<<Project End>>", plain, flags=re.DOTALL)

# create a dictionary which are the labels for the training sample
labels = [
    {
        'case_number': '98.226D',
        'project_address': '571 Jersey Street',
        'lot_number': '033',
        'assessor_block': '6540',
        'project_descr': 'Request for Discretionary Review of Building Permit Application No. 9722606 to construct a third-level bedroom suite and roof deck to an existing two-story single-family residence',
        'type_district': 'RH-2',
        'type_district_descr': 'house, two-family',
        'speakers': 'None',
        'action': 'Continued as proposed',
        'ayes': ['Chinchilla', 'Theoharis', 'Antenore', 
            'Hills', 'Joe', 'Martin', 'Mills'],
        'noes': [],
        'vote': '7-0',
    },
    {
        'case_number': '98.251C',
        'project_address': '154 Coleridge Street',
        'lot_number': '22',
        'assessor_block': '5642',
        'project_descr': 'Request for authorization of a conditional use to modify a condition of approval of Commission Motion No. 11774 to accommodate one handicapped-accessible dwelling unit in subject three-unit residential building',
        'type_district': 'RH-2',
        'type_district_descr': 'house, two-family',
        'height_and_bulk_district': '40-x',
        'action': 'Continued as proposed',
        'speakers': 'None',
        'ayes': ['Chinchilla', 'Theoharis', 'Antenore', 
            'Hills', 'Joe', 'Martin', 'Mills'],        
        'noes': [],
        'vote': '7-0'
    },
    {
        'case_number': '97.686C',
        'project_address': '1100 Grant Avenue',
        'lot_number': '10',
        'assessor_block': '162',
        'project_descr': 'Request for Conditional Use authorization under Sections 812.49 and 812.20 of the Planning Code to establish a financial service of approximately 3,600 feet in the CR-NC (Chinatown Residential Neighborhood Commercial) District',
        'height_and_bulk_district': '50-N',
        'action': 'Continued as proposed',
        'speakers': 'None',
        'ayes': ['Chinchilla', 'Theoharis', 'Antenore', 
            'Hills', 'Joe', 'Martin', 'Mills'],
        'noes': [],
        'vote': '7-0'
    },
    {
        'case_number': '98.238ET',
        'project_name': 'Bridge District Amendment','
        'project_descr': 'Consideration of a proposal to amend Section 1010 of the City Planning Code to clarify that the Golden Gate Bridge Highway and Transportation District is exempt from the regulations of Article 10 of the Planning Code which authorizes the designation of landmark structures and establishes various procedures for reviewing proposals to demolish or alter landmarks',
        'speakers': ['David Bahlman', 'Gee Gee Platt'],
        'action': 'approved',
        'ayes': ['Chinchilla', 'Theoharis', 'Antenore', 
            'Joe', 'Martin', 'Mills'],
        'excused': ['Hills'],
        'noes': [],
        'vote': '6-0-1',
        'action_name': 'resolution no. 14633'
    },
    {
        'case_number': '98.341T',
        'project_name': 'Affordable Child Care Amendment',
        'project_descr': 'Proposal to amend Section 314.5 of the Planning Code to expand the sources and eligible uses of monies in the Affordable Child Care Fund',
        'speakers': [],
        'action': 'approved',
        'ayes': ['Chinchilla', 'Theoharis', 'Antenore', 
            'Hills', 'Joe', 'Martin', 'Mills'],
        'noes': [],
        'vote': '7-0',
        'action_name': 'resolution no. 14634'
    },
    {
        'case_number': '97,470E',
        'project_address': '475 Brannan Street',
        'lot_number': '31',
        'assessor_block': '3787',
        'project_name': 'Public Hearing on the Draft Environmental Impact Report',
        'project_descr': 'projct would add two stories to an existing two-story-plus-basement building...the project would require a rezoning of the existing 50-foot height limit to 65 feet to permit construction of the 58-foot-tall project',
        'type_district': 'SSO (Service Secondayr Office)',
        'speakers': ['David Bahlman', 'Judy West', 'John Paulson', 'Wendy Earl',''
        'Bob Meyers', 'Jerry Marker', 'Roger Geasham', 'Allison Fuller', 'David Coleen'],
        'action': 'meeting held. public hearing closed',
    },
    {
        'case_number': '98.136C',
        'address': '540 and 590 Van Ness Avenue',
        'lot_number': '13',
        'assessor_block': '766',
        'project_descr': 'conditional use authorization to establish a large fast food restaurant',
        'type_district': 'RC-4',
        'type_district_descr': 'High Density Residential-Commercial',
        'height_and_bulk_district': '130-V',
        'Speakers': ['Robert McCarthy'],
        'action': 'approved with conditions as drafted',
        'ayes': ['Chinchilla', 'Theoharis', 'Antenore', 
            'Hills', 'Joe', 'Martin', 'Mills'],
        'noes': [],
        'vote': '7-0',
        'action_name': 'resolution no. 14636'
    },
    {
        'case_number': '98.186C',
        'project_address': '4207 Judah Street',
        'lot_number': '37',
        'assessor_block': '1806',
        'project descr': 'conditional use authorization under section 303(e) of planning code to extend termination date of nonconforming bar from 1999 to 2009 to allow bar to continue operating until 2:00 am',
        'type_district': 'RM-1',
        'type_district_descr': 'residential, mixed, low-density',
        'height_and_bulk_district': '40-X',
        'speakers': ['Patrick Than', 'Lil Palermo'],
        'action': 'approved with conditions as drafted',
        'ayes': ['Chinchilla', 'Theoharis', 'Antenore', 
            'Hills', 'Joe', 'Martin', 'Mills'],
        'noes': [],
        'vote': '7-0',
        'action_name': 'resolution no. 14637'
    },
    {
        'case_number': '98.127C',
        'project_address': '1200 9th Avenue',
        'lot_number': '35',
        'lot_number_2': '44',
        'assessor_block': '1742',
        'project_descr': 'modification of previously approved conditional use authorization for development of a lot exceeding 10,000 square feet and establishment of a retial pet store, to allow a general convenience retail/pharmacy use rather than previously approved pet store',
        'type_district': 'NC-2',
        'type_district_descr': 'small-scale neighborhood commercial',
        'height_and_bulk_district': '40-X',
        'speakers': ['Robert McCarthy', 'Steven', 'Lewens',
                     'Bob Planthold', 'Pat Ann Miller', 'Eric Bianco', 'Deboarh Lises',
                     'Dr. Rob Eric', 'Dennis Quinn', 'James Hanley',
                     'Harvey Vickens', 'John Bardis'],
        'action': 'approve with condition as modified',
        'modifications': ['security in parking lot to move cars out within an hour',
                          'pharmacist on site from 8 a.m. to 9 p.m.', 
                          'loading/deliveries on site only', 
                          'van size not to exceed 30 feet', 
                          'hours of operations 7a.m. to 11 p.m.',
                          'project sponsor shall continue to work with staff on project',
                          'sign language as ready by Bob Passmore',
                          'establish a liaison officer', 
                          'loading hours developed in consultation with Planning Department'],
        'ayes': ['chinchilla', 'theoharis', 'martin', 'mills'],
        'noes': ['antenore', 'hills', 'joe'],
        'vote': '4-3',
        'action_name': 'resolution no. 14638'
    },
    {
        'case_number': '98.285C',
        'project_address': '1640 Stockton Street',
        'lot_number': '15',
        'assessor_block': '103',
        'project_descr': 'request for discretionary review of building permit application no. 9725734, proposing to merge a four-unit building into a single-family dwelling',
        'type_district': 'RH-3',
        'type_district_descr': 'house, three-family',
        'speakers': [],
        'action': 'without hearing, continued to 6/18/98',
        'ayes': ['Chinchilla', 'Theoharis', 'Antenore', 
            'Hills', 'Joe', 'Martin', 'Mills'],
        'noes': [],
        'vote': '7-0',
    },
    {
        'case_number': '98.246D',
        'project_address': '3230 Baker Street',
        'lot_number': '025',
        'assessor_block': '0926',
        'project_descr': 'request for discretionary review of building permit application 9725973, proposing to construct an additional level to existing single-unit house',
        'type_district': 'RH-1',
        'type_district_descr': 'house, one-family',
        'action': 'discretionary review request withdrawn',
    },
    {
        'case_number': '98.254D',
        'project_address': '41 Norfolk Street',
        'lot_number': '051',
        'assessor_block': '3521',
        'project_descr': 'request for discretionary review of building permit application no. 9713455, proposing to construct a new three-story building with two live/work units on a vacant lot',
        'type_district': 'SLR',
        'type_district_descr': 'service/light/industrial/residential mixed use',
        'Speakers': [],
        'Action': 'without hearing, continued indefinitely',
        'ayes': ['Chinchilla', 'Theoharis', 'Antenore', 
            'Hills', 'Joe', 'Martin', 'Mills'],
        'noes': [],
        'vote': '7-0',
    },
    {
        'case_number': '98.274C',
        'project_address': '1401 18th street',
        'lot_number': '01',
        'assessor_block': '4036',
        'project_descr': 'request for conditional use authorization to eliminate required off-street parking, in order to install an ATM in existing garage space',
        'type_district': 'nc-2',
        'type_district_descr': 'small-scale neighborhood commercial',
        'height_and_bulk_district': '40-X',
        'action': 'continued as proposed',
        'speakers': [],
        'ayes': ['Theoharis', 'Antenore', 'Hills', 'Joe', 'Mills'],
        'noes': [],
        'absent': ['Chinchilla', 'Martin'],
        'vote': '5-0',
    },
    {
        'case_number': '98.222D',
        'project_address': '135 Miguel Street',
        'lot_number': '010',
        'assessor_block': '6683',
        'project_descr': 'request for discretionary review of building permit application nos. 9800270 and 9800271, proposing to demolish two structures and construct a new three-story, single-family dwelling',
        'type_district': 'RH-1',
        'type_district_descr': 'house, one-family',
        'action': 'continue as proposed',
        'speakers': [],
        'ayes': ['Theoharis', 'Antenore', 'Hills', 'Joe', 'Mills'],
        'noes': [],
        'absent': ['Chinchilla', 'Martin'],
        'vote': '5-0',
    },
    {
        'case_number': '98.377D',
        'project_address': '1 La Avanzada Street, Sutro Tower',
        'lot_number': '003',
        'assessor_block': '2724',
        'project_descr': 'request for discretionary review of building permit application no. 9805770, to construct three new concrete pads outside existing building and two new rooftop enclosures',
        'type_district': 'rh-1(D)',
        'type_district_descr': 'house, one-family, detached',
        'action': 'continue as proposed',
        'ayes': ['Theoharis', 'Antenore', 'Hills', 'Joe', 'Mills'],
        'noes': [],
        'absent': ['Chinchilla', 'Martin'],
        'vote': '5-0',
    },
    {
        'case_number': '98.290D/DD',
        'project_address': '253 29th Avenue',
        'lot_number': '006',
        'assessor_block': '1389',
        'project_descr': 'request for discretionary review of building permit application no. 9803645, proposing to construct two-story addition at rear of two-story single-family dwelling',
        'type_district': 'RH-1',
        'type_district_descr': 'house, one-family',
        'action': 'discretionary review request withdrawn'
    },
    {
        'case_number': '98.229D',
        'project_address': '253 26th Avenue',
        'lot_number': '009',
        'assessor_block': '1386',
        'project_descr': 'request for discretionary review of building permit application no. 9723790S to demolish existing one-unit house and replace it with three-unit residential building',
        'type_district': 'RH-1',
        'type_district_descr': 'house, one-family',
        'action': 'discretionary review request withdrawn',
    },
    {
        'case_number': '98.227ETZ',
        'project_name': 'Historic Sign District',
        'project_descr': 'add two new sections to Planning Code, creating concept of an historic sign and historic sign district which would allow signs deemed historic to be restored, updated and maintained as a conditional use',
        'speakers': ['Ruben Glickman', 'Judy West'],
        'action': 'text amendment',
        'ayes': ['Theoharis', 'Antenore', 
            'Hills', 'Mills'],
        'noes': ['Joe'],
        'absent': ['Chinchilla', 'Martin'],
        'vote': '4-1',
        'action_name': 'motion no. 14640',
        'action_2': 'map amendment',
        'ayes_2': ['Theoharis', 'Antenore', 
            'Hills', 'Mills'],
        'noes_2': ['Joe'],
        'absent_2': ['Chinchilla', 'Martin'],
        'vote_2': '4-1',
        'action_name_2': 'motion no. 14641'
    },
    {
        'case_number': '89.589BXHE',
        'project_address': '300 Howard Street/199 Fremont Street',
        'lot_number': '5, 6, 7, 8, 9',
        'assessor_block': '3719',
        'district_type': 'C-3-O(SD)',
        'district_type_descr': 'downtown office, special development district',
        'height_and_bulk_district': '350-S',
        'project_descr': 'modifications to annual limit approval motion no. 13218 concerning conditions relating to employment to conform to current city and state regulations',
        'speakers': [],
        'action': 'without hearing, continued to 6/18',
        'ayes': ['Theoharis', 'Antenore', 
            'Hills', 'Joe', 'Mills'],
        'noes': [],
        'absent': ['Chinchilla', 'Martin'],
        'vote': '5-0',
    },
    {
        'case_number': '97.629C',
        'project_address': '300 Gough Street',
        'lot_number': '008',
        'assessor_block': '816',
        'project_descr': 'request for conditional use authorization to develop site in excess of 10,000 quare feet by constructing four-story over a bu-level garage',
        'type_district': 'Hayes-Gough Neighborhood Commercial District',
        'type_district_descr': 'Hayes-Gough Neighborhood Commercial District',
        'height_and_bulk_district': '50-X',
        'action': 'without hearing, continued to 6/18',
        'speakers': [],
        'ayes': ['Theoharis', 'Antenore', 
            'Hills', 'Joe', 'Mills'],
        'noes': [],
        'absent': ['Chinchilla', 'Martin'],
        'vote': '5-0',
    },
    {
        'case_number': '98.251C',
        'project_address': '154 Coleridge Street',
        'lot_number': '22',
        'asessor_block': '5642',
        'project_descr': 'request for conditional use to modify condition of approval of commission motion no. 11774 permitting reduction from six to four off-street parking spaces',
        'type_district': 'rh-2',
        'type_district_descr': 'house, two-family',
        'height_and_bulk_district': '40-X',
        'speakers': ['Mark Rosenbaum',' Dennis Singer'],
        'action': 'approved with conditions as drafted',
        'ayes': ['Theoharis', 'Antenore', 
            'Hills', 'Joe', 'Mills'],
        'absent': ['Chinchilla', 'Martin'],
        'vote': '5-0',
        'action_name': 'resolution no. 14642'
    },
    {
        'case_number': '98.506D/DD',
        'project_address': '1415 Indiana Street',
        'lot_number': '017',
        'asessor_block': '4293',
        'project_descr': 'request for discretionary review of building permit application no. 9724661, proposing to consruct 18 live/work units and 18 parking spaces on a vacant lot',
        'type_district': 'M-2',
        'type_district_descr': 'heavy industrial',
        'speakers': [],
        'action': 'without hearing, continued to 6/25',
        'ayes': ['Theoharis', 'Antenore', 
            'Hills', 'Joe', 'Mills'],
        'noes': [],
        'absent': ['Chinchilla', 'Martin'],
        'vote': '5-0',
    },
    {
        'case_number': '98.311D',
        'project_address': '1738 44th Avenue',
        'lot_number': '022',
        'assessor_block': '2006',
        'project_descr': 'request for discretionary review of building permit application no. 9801485, proposing to legalize an existing two-story rear addition and further extend rear wall of house to add master bedroom over basemenet',
        'type_district': 'RH-1',
        'type_district_descr': 'house, one-family',
        'speakers': ['Anthony Fong'],
        'action': 'Take D.R. approve staff recommended modifications if project sponsor has not submitted revised plans for in 30 days, department will disapprove',
        'ayes': ['Theoharis', 'Antenore',
            'Hills', 'Joe', 'Mills'],
        'noes': [],
        'absent': ['Chinchilla', 'Martin'],
        'vote': '5-0'
    },
    {
        'case_number': '97.367D',
        'project_address': '1233 Howard Street',
        'lot_number': '088',
        'assessor_block': '3729',
        'project_descr': 'request for discretionary review of building permit application no. 9710318, proposing to convert an existing commercial space into 24 live/work units, including 21-foot vertical addition',
        'type_district': 'SLR',
        'type_district_descr': 'service/light industrial/residential mixed use',
        'speakers': ['John Elberling', 'Sue Hestor', 'Simon Akhavan',
                     'Alan Grosstimen', 'Tom Brown', 'Maureen Blackburn'],
        'action': 'take D.R. approve staff recommendation - 20 live/work units- up to 4 non live-work space on ground floor',
        'ayes': ['Theoharis', 'Antenore', 
            'Hills', 'Joe', 'Mills'],
        'noes': [],
        'absent': ['Chinchilla', 'Martin'],
        'vote': '5-0',
    },
    {
        'case_number': '98.313D',
        'project_address': '378 Diamond Street',
        'lot_number': '014',
        'assessor_block': '2750',
        'project_descr': 'request for discretionary review of building permit application no. 9803972, to construct a new second-story addition to existing single-family residence',
        'type_district': 'RH-2',
        'type_district_descr': 'house, two-family',
        'speakers': [],
        'action': 'Approved as proposed',
        'ayes': ['Chinchilla', 'Theoharis', 'Hills', 'Joe', 'Martin', 'Mills'],
        'absent': ['Antenore'],
        'noes': [],
        'vote': '6-0',
    },
    {
        'case_number': '98.410D/DD',
        'project_address': '483 Hoffman Avenue',
        'lot_number': '017',
        'assessor_block': '6503',
        'project_descr': 'request for discretionary review of building permit application no. 9802525, to fill in under a pop-out section approx. 22 feet above grade and construct a rear deck',
        'type_district': 'RH-2',
        'type_district_descr': 'house, two-family',
        'speakers': [],
        'action': 'approved as proposed',
        'ayes': ['Chinchilla', 'Theoharis',
            'Hills', 'Joe', 'Martin', 'Mills'],
        'absent': ['Antenore'],
        'noes': [],
        'vote': '6-0',
    },
    {
        'case_number': '98.287C',
        'project_address': '492 Broadway',
        'lot_number': '16, 17, 18',
        'assessor_block': '144',
        'project_descr': 'request for conditional use authorization to allow full-service restaurant with gross floor area of 4,870 square feet',
        'type_district': 'Broadway Neighborhood Commercial District',
        'heigh_and_bulk_district': '65-A',
        'speakers': [],
        'action': 'approved as proposed',
        'ayes': ['Chinchilla', 'Theoharis', 
            'Hills', 'Joe', 'Martin', 'Mills'],
        'noes': [],
        'absent': ['Anetenore'],
        'vote': '6-0'
    },
    {
        'case_number': '97.499Q',
        'project_address': '987-97 14th Street',
        'lot_number': '72A',
        'assessor_block': '3540',
        'project_descr': 'six unit residential condominium conversion subdivision',
        'type_district': 'RH-3',
        'type_district_descr': 'house, three-family',
        'speakers': [],
        'action': 'approved',
        'ayes': ['Chinchilla', 'Theoharis', 
            'Hills', 'Joe', 'Martin', 'Mills'],
        'noes': [],
        'absent': ['Antenore'],
        'vote': '6-0',
        'action_name': 'motion no. 14643'
    },
    {
        'case_number': '98.155ET',
        'project_name': '24th/Noe Food Service Amendment',
        'project_descr': 'proposal to amend Planning Code Sections 728 and 703.2 to prohibit special grocery and retail coffee stores and accessory take-out food service use associated with these stores in the 24th Street/Noe Valley Neighborhood Commercial District',
        'speakers': ['Tricia Hollenberg', 'Terri Harte', 'Jean Amos',
                     'Claire Pilcher', 'Suzanne Racliffe', 'Yvonne Borg', 'Eleanore Gerhardt',
                     'Harry Stern', 'John Bruun', 'Drone Barrett', 'Bill Barrett'],
        'action': 'approved',
        'ayes': ['Chinchilla', 'Theoharis',
            'Hills', 'Joe', 'Martin', 'Mills'],
        'noes': [],
        'absent': ['Antenore'],
        'vote': '6-0'
    }
    {
        'case_number': '97.358CV',
        'project_address': '105 Miles Street',
        'lot_number': '54',
        'assessor_block': '243',
        'project_descr': 'request for conditional use authorization to add approx. 6154 square feet of floor area to an existing recreational facility presently containing approx. 7794 square feet',
        'type_district': 'RM-4',
        'type_district_1': 'nob hill special use district',
        'type_district_descr': 'residential, mixed, high-density',
        'height_and_bulk_district': '65-A',
        'speakers': ["Walter O'Harie", 'Joe Brown', 'Mark Rosentein', 'Bruce Anderson',
                     'Kevin Jernigan', 'Lynette Crane',' Ruth C. Jacobs',
                     'Jack Hornor', 'Martin Vierjahan', 'Jerladine Gotera', 
                     'Colleen Hollisy', 'Victoria Archlow-Debro', 'David Ronce',
                     'Anne Ronce', 'Deboarh Blackburn', 'Carole A. Obley', 'Jim McCormick',
                     'Tho On', 'Mike Martusello', 'Simone Blatner', "Owen O'Donnell",
                     'Gene Gillis', 'Steve Lau', 'Dwight James Simpson', 'Brian Guan',
                     'Alexandra Crichlow', 'Marrianne Rothe', 'Dexter Louie',
                     'Paul Seipp', 'Paul S. Saint-Pierre', 'John Hussey',
                     'Anthony Y. Kelly'],
        'action': 'continued to 8/20/98',
        'ayes': ['Chinchilla', 'Theoharis', 
            'Hills', 'Joe', 'Martin', 'Mills'],
        'noes': [],
        'absent': ['Antenore'],
        'vote': '6-0'
    },
    {
        'case_number': '97.358CV',
        'project_address': '105 Miles Street',
        'lot_number': '54',
        'assessor_block': '243',
        'project_descr': 'parking variance sought; proposal will provide four off-site off-street parking spaces through month-to-month lease where four permanent off-street parking spaces are required per planning code sections 151 and 159',
        'type_district': 'RM-4',
        'type_district_1': 'nob hill special use district',
        'type_district_descr': 'residential, mixed, high-density',
        'height_and_bulk_district': '65-A',
        'speakers': ["Walter O'Harie", 'Joe Brown', 'Mark Rosentein',
                     'Bruce Anderson', 'Kevin Jernigan', 'Lynette Crane', 'Ruth C. Jacobs',
                     'Jack Hornor', 'Martin Vierjahan', 'Jerladine Gotera', 'Colleen Hollisy',
                     'Victoria Archlow-Debro', 'David Ronce', 'Anne Ronce', 'Deboarh Blackburn',
                     'Carole A. Obley', 'Jim McCormick', 'Tho On', 'Mike Martusello',
                     'Simone Blatner', "Owen O'Donnell", 'Gene Gillis', 'Steve Lau',
                     'Dwight James Simpson', 'Brian Guan', 'Alexandra Crichlow', 'Marianne Rothe',' Dexter Louie',
                     'Paul Seipp', 'Paul S. Saint-Pierre', 'John Hussey', 'Anthony Y. Kelly'],
        'action': 'continued to 8/20/98',
        'ayes': ['Chinchilla', 'Theoharis', 
            'Hills', 'Joe', 'Martin', 'Mills'],
        'noes': [],
        'absent': ['Antenore'],
        'vote': '6-0'
    },
    {
        'case_number': '97.629C', 
        'project_address': '300 Gough Street',
        'lot_number': '008',
        'assessor_block': '816',
        'project_descr': 'request for conditional use authorization to develop a site in excess of 10,000 square feet and a use size in excess of 3,000 square feet by constructing a four-story over a sub-level garage, mixed commercial and residential building',
        'type_distrct': 'Hayes-Gough Neighborhood Commercial District',
        'height_and_bulk_district': '50-X',
        'speakers': ['John Caldwell', 'George Groan'],
        'action': 'approved as amended',
        'modifications': [
            'all residential units excluding the three units designated as affordable (BMR) units shall be rental units for no less than 10 years', 
            'the three units designated as affordable units shall be rental units for 50 years',
            'all delivery trucks to the retail space shall turn off their engines during delivery, which shall take place inside the garage',
            'all delivers by trucks not under Walgreens control shall be limited to the hours of 6:30 a.m. to midnight',
            'deliveries by semi-truck under Walgreens control shall be further limited to the hours of 8:00 p.m. to midnight',
            'semi-trucks under walgreens control shall access the garage from linden street and exit onto fell street',
            'failure to comply with condition nos. 3(b) and 4(c) would be considered a violation, subject to a fine of $10,000 payable into the Mayors Affordable C?hild Care Fund',
        ],
        'ayes': ['Chinchilla', 'Theoharis', 
            'Joe', 'Martin', 'Mills'],
        'noes': ['Hills'],
        'absent': ['Antenore'],
        'action_name': 'motion no. 14645'
    },
    {
        'case_number': '98.274C',
        'project_address': '1401 18th Street',
        'lot_number': '01',
        'assessor_block': '4036',
        'project_descr': 'request for conditional use authorization to eliminate required off-street parking space to install an automatic teller machine (ATM) in an existing garage space',
        'type_district': 'NC-2',
        'type_district_descr': 'small-scale neighborhood commercial',
        'height_and_bulk_district': '40-X',
        'speakers': ['Luther Greulich', 'Noe Hyman', 'B. Schmender',
                     'Kenneth Overholt', 'Charles Patton'],
        'action': 'intent to disapprove',
        'ayes': ['Chinchilla', 'Hills', 'Joe', 'Martin', 'Mills'],
        'noes': [],
        'absent': ['Theoharis', 'Antenore'],
        'vote': '5-0',
    },
    {
        'case_number': '98.105C',
        'project_address': '300 Gaven Street',
        'lot_number': '01',
        'assessor_block': '5846',
        'lot_number_2': '32',
        'assessor_block_2': '5847',
        'project_descr': 'request for conditional use authorization to expand existing private elementary school on San Francisco School property under section 209.3(g) of Planning Code',
        'type_district': 'RH-1',
        'type_district_descr': 'house, one-family',
        'height_and_bulk_district': '40-X',
        'speakers': ['Penny Sarmiento', 'Karen Goodkin', 'Dolores Elkin',
                     'Peter Fuents-Afflick', 'Helene Wright',
                     'Monica Herbert', 'Brian McCarthey', 'Esperanza Martinez', 'Emily Huang',
                     'Ravi Anand', 'Terry Edeli'],
        'action': 'approved as amended',
        'modifications': [
            'the operator or staff shall monitor drop-off and pick-up of students to discourage double parking and excessive noise',
            'notices ahll be sent to parnets on a quarterly basis requesting no double parking in front of the buildling',
            'applicant/project sponsor shall appoint a community liaison to deal with such issues as parking and other related matters of concern to nearby residents',
            'the applicant shall report the name and telephone number of the liaison to reisdents within a 150-foot radius and the zoning administrator for reference',
            'project sponsor ahll provide a year-end report on parking and related issues for review by planning staff by january 30, 1999 and a second report by july 30, 1999'
        ],
        'ayes': ['Chinchilla',
            'Hills', 'Joe', 'Martin', 'Mills'],
        'absent': ['Theoharis', 'Antenore'],
        'noes': [],
        'vote': '5-0',
        'action_name': 'motion no. 14646'
    },
    {
        'case_number': '98.307D',
        'project_address': '2425 Hyde Street',
        'lot_number': '002',
        'assessor_block': '0047',
        'project_descr': 'request for discretionary review of building permit application no. 9725734 to merge a four-unit building into a single-family dwelling',
        'type_district': 'RH-3',
        'type_district_descr': 'house, three-family',
        'speakers': [],
        'action': 'continued to 6/25/98',
        'ayes': ['Chinchilla', 'Hills', 'Joe', 'Martin', 'Mills'],
        'noes': [],
        'absent': ['Antenore', 'Theoharis'],
        'vote': '5-0',
    },
    {
        'case_number': '98.222D',
        'project_address': '135 Miguel Street',
        'lot_number': '010',
        'assessor_block': '6683',
        'project_descr': 'request for discretionary review of building permit application nos 9800270 and 9800271, to demolish two structures and construct a new three-story, single-family dwelling',
        'type_district': 'RH-1',
        'type_district_descr': 'house, one-family',
        'speakers': [],
        'action': 'continued to 6/25/98',
        'ayes': ['Chinchilla', 'Hills', 'Joe', 'Martin', 'Mills'],
        'noes': [],
        'absent': ['Antenore', 'Theoharis'],
        'vote': '5-0',
    },
    {
        'case_number': '98.334D',
        'project_address': '381 Douglass Street',
        'lot_number': '028',
        'assessor_block': '2699',
        'project_descr': 'request for discretionary review of building permit application no. 9804634, to construct a second- and third-story addition off the rear of the house',
        'type_district': 'RH-2',
        'type_district_descr': 'house, two-family',
        'speakers': ['Robb Wall', 'Chris Westergaard', 'Tom Simlock',
                     'Alberto Orsuin'],
        'action': 'Take D.R. and modify the prooject',
        'ayes': ['Chinchilla', 'Hills', 'Joe', 'Martin', 'Mills'],
        'noes': [],
        'absent': ['Antenore', 'Theoharis'],
        'vote': '5-0'
    },
    {
        'case_number': '98.3509D/DD',
        'project_address': '2646 Broderick Street',
        'lot_number': '014',
        'assessor_block': '0954',
        'project_descr': 'request for discretionary review of building permit application no. 9806740, proposing to construct two-story addition at rear of existing two-story, single-family dwelling',
        'type_district': 'RH-1',
        'type_district_descr': 'house, one-family',
        'speakers': ['Janet Raintree', 'Terry Louertein', 'Joseph Welch', 'Don Keslsachorse', 'Margaret Rae',
                     'Marty Zwick', 'Liz Welch'],
        'action': 'approved',
        'ayes': ['Chinchilla', 'Hills', 'Joe', 'Martin', 'Mills'],
        'noes': [],
        'absent': ['Antenore', 'Theoharis'],
        'vote': '5-0'
    },
    
]